name: Run Web Scraper

on:
  workflow_dispatch:        # allows manual trigger from GitHub UI


jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Run scraper
        run: dotnet run --configuration Release --project WebScrapper/WebScrapper.csproj
